### ISSUE TITLE
Mean is calculated over wrong axis [BUG]

### ISSUE THREAD

**Issue by jjpass00** [franneck94/TensorCross#44]
In `_run_search()` -func in `search_cv.py` the code calculates the `mean_val_scores` as follows

`mean_val_scores = np.mean(self.results_["val_scores"], axis=0)`

This calculates mean over different model parameter combinations with the same test/validation set and thus returns the column which had with all combinations on average the smallest score. The mean should be calculated over scores within each combination.

To fix this bug one should calculate the `mean_val_scores` as follows:

`mean_val_scores = np.mean(self.results_["val_scores"], axis=1)`

**Comment by franneck94** [comment]
Fixed in 0.4.3
