### ISSUE TITLE
Does not work with tensorflow-macos [BUG]

### ISSUE THREAD

**Issue by Wissiak** [franneck94/TensorCross#45]
Pip install does not work with tensorflow-macos which is required for M1/M2 machines:
![Screenshot 2023-03-11 at 18 34 17](https://user-images.githubusercontent.com/31206249/224503234-4e7ad454-7d0c-41ab-854d-294406a34ac7.png)

Having installed the following packages:
tensorflow-macos              2.9.0
tensorflow-metal                0.5.1

**Comment by franneck94** [comment]
Fixed with #46

**Comment by thomasruegg** [comment]
Yo that was fast 👏
